=== OntoUML/ontouml-js/resources/schemas/diagram.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ontouml.org/ontouml-schema/2021-02-26/Diagram",
  "description": "An array containing the values defined for an enumeration. Should only be used if the class is stereotyped as <<enumeration>>, otherwise, the value of this field should be null.",
  "type": "object",
  "properties": {
    "type": {
      "const": "Diagram"
    },
    "id": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#id"
    },
    "name": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "description": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "contents": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "array",
          "items": {
            "oneOf": [
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/ClassView"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/RelationView"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/GeneralizationView"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/GeneralizationSetView"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/PackageView"
              }
            ]
          }
        }
      ]
    },
    "owner": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#reference"
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": ["type", "id"]
}

=== OntoUML/ontouml-js/__tests__/libs/complexity/examples/paperExample.json
[
  {
    "id": "0",
    "type": "Diagram",
    "name": "Cluster of Marriage",
    "description": null,
    "owner": {
      "type": "Package",
      "id": "mRPQoc6GAqACAgBO"
    },
    "contents": [
      {
        "type": "Shape",
        "id": "marriage-shape",
        "source": {
          "type": "Class",
          "id": "rPmS4c6GAqACAgkB"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "husband-shape",
        "source": {
          "type": "Class",
          "id": "eNSS4c6GAqACAgi8"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "wife-shape",
        "source": {
          "type": "Class",
          "id": "6sSS4c6GAqACAgiw"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "person-shape",
        "source": {
          "type": "Class",
          "id": "Zunwoc6GAqACAgWp"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "man-shape",
        "source": {
          "type": "Class",
          "id": "NNkS4c6GAqACAgc7"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "woman-shape",
        "source": {
          "type": "Class",
          "id": "bGkS4c6GAqACAgco"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "involves-husband-line",
        "source": {
          "type": "Relation",
          "id": "jLuS4c6GAqACAgkd"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "involves-wife-line",
        "source": {
          "type": "Relation",
          "id": "YfBS4c6GAqACAgk8"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "woman-|>person-line",
        "source": {
          "type": "Generalization",
          "id": "tgMS4c6GAqACAgfV"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "man-|>person-line",
        "source": {
          "type": "Generalization",
          "id": "KtMS4c6GAqACAgfm"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "wife-|>woman-line",
        "source": {
          "type": "Generalization",
          "id": "VDaS4c6GAqACAgji"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "husband-|>man-line",
        "source": {
          "type": "Generalization",
          "id": "BD6S4c6GAqACAgjz"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Label",
        "id": "genderset-label",
        "source": {
          "type": "GeneralizationSet",
          "id": "9gmG4c6GAqACAgqv"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      }
    ]
  },
  {
    "id": "1",
    "type": "Diagram",
    "name": "Cluster of Emplyoment",
    "description": null,
    "owner": {
      "type": "Package",
      "id": "mRPQoc6GAqACAgBO"
    },
    "contents": [
      {
        "type": "Shape",
        "id": "emplyoment-shape",
        "source": {
          "type": "Class",
          "id": "aHWy4c6GAqACAgrV"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "employee-shape",
        "source": {
          "type": "Class",
          "id": "Q0Gy4c6GAqACAgq3"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "organization-shape",
        "source": {
          "type": "Class",
          "id": "rgey4c6GAqACAgrh"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "person-shape",
        "source": {
          "type": "Class",
          "id": "Zunwoc6GAqACAgWp"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "involves-employee-line",
        "source": {
          "type": "Relation",
          "id": "6Epy4c6GAqACAgsV"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "involves-employer-line",
        "source": {
          "type": "Relation",
          "id": "etZy4c6GAqACAgsu"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "employee-|>person-line",
        "source": {
          "type": "Generalization",
          "id": ".zxy4c6GAqACAgsC"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      }
    ]
  },
  {
    "id": "2",
    "type": "Diagram",
    "name": "Cluster of Car Ownership",
    "description": null,
    "owner": {
      "type": "Package",
      "id": "mRPQoc6GAqACAgBO"
    },
    "contents": [
      {
        "type": "Shape",
        "id": "car-ownership-shape",
        "source": {
          "type": "Class",
          "id": "dNQK4c6GAqACAguT"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "car-shape",
        "source": {
          "type": "Class",
          "id": "fnIK4c6GAqACAguf"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "car-agency-shape",
        "source": {
          "type": "Class",
          "id": "5Ffy4c6GAqACAguD"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Shape",
        "id": "organization-shape",
        "source": {
          "type": "Class",
          "id": "rgey4c6GAqACAgrh"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "involves-car-line",
        "source": {
          "type": "Relation",
          "id": "Yg8q4c6GAqACAg3J"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "involves-owner-line",
        "source": {
          "type": "Relation",
          "id": "jOCq4c6GAqACAg3c"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      },
      {
        "type": "Line",
        "id": "car-agency-|>organization-line",
        "source": {
          "type": "Generalization",
          "id": "..5K4c6GAqACAgxj"
        },
        "field": null,
        "points": null,
        "font": null,
        "line": null,
        "background": null,
        "visibility": null,
        "elements": null
      }
    ]
  },
  {
    "id": "3",
    "type": "Diagram",
