=== OntoUML/ontouml-js/resources/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ontouml.org/ontouml-schema/2021-02-26/Package",
  "description": "An object representing a package element. Mandatory fields: constant \"type\": \"Package\", \"id\", \"name\", \"elements\", \"propertyAssignments\". Additional fields NOT allowed.",
  "type": "object",
  "properties": {
    "type": {
      "const": "Package"
    },
    "id": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#id"
    },
    "name": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "description": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "propertyAssignments": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#propertyAssignments"
    },
    "contents": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "oneOf": [
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Package"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Class"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Relation"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/GeneralizationSet"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Generalization"
              }
            ]
          }
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": ["type", "id", "name", "description", "contents", "propertyAssignments"]
}

=== OntoUML/ontouml-js/test_models/valids/subkind1.json
{
  "type": "Package",
  "id": "SaL.mg6D.AAAAQBO",
  "name": "Subkind1",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "WaL.mg6D.AAAAQBQ",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "NaL.mg6D.AAAAQBR",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "taL.mg6D.AAAAQBS",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "taL.mg6D.AAAAQBT",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "taL.mg6D.AAAAQBU",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "daL.mg6D.AAAAQBV",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "daL.mg6D.AAAAQBW",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "daL.mg6D.AAAAQBX",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "9aL.mg6D.AAAAQBY",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "isExtensional": null,
      "isPowertype": null,
      "order": null,
      "allowed": null,
      "id": "9aL.mg6D.AAAAQBZ",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Package",
      "id": "CK0hmg6D.AAAAQXz",
      "name": "Diagram1",
      "description": null,
      "propertyAssignments": null,
      "contents": [
        {
          "type": "Class",
          "isExtensional": null,
          "isPowertype": null,
          "order": null,
          "allowed": null,
          "id": "1DWBmg6D.AAAAQWV",
          "name": "Person",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["kind"],
          "isAbstract": false,
          "isDerived": false
        },
        {
          "type": "Class",
          "isExtensional": null,
          "isPowertype": null,
          "order": null,
          "allowed": null,
          "id": "vmFBmg6D.AAAAQXE",
          "name": "Man",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["subkind"],
          "isAbstract": false,
          "isDerived": false
        },
        {
          "type": "Class",
          "isExtensional": null,
          "isPowertype": null,
          "order": null,
          "allowed": null,
          "id": "kX.Rmg6D.AAAAQYU",
          "name": "Woman",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["subkind"],
          "isAbstract": false,
          "isDerived": false
        }
      ]
    },
    {
      "type": "Generalization",
      "id": "uWFBmg6D.AAAAQXJ",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "1DWBmg6D.AAAAQWV"
      },
      "specific": {
        "type": "Class",
        "id": "vmFBmg6D.AAAAQXE"
      }
    },
    {
      "type": "Generalization",
      "id": "RX.Rmg6D.AAAAQYZ",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "1DWBmg6D.AAAAQWV"
      },
      "specific": {
        "type": "Class",
        "id": "kX.Rmg6D.AAAAQYU"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "uczRmg6D.AAAAQZM",
      "name": "Person",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "uWFBmg6D.AAAAQXJ"
        },
        {
          "type": "Generalization",
          "id": "RX.Rmg6D.AAAAQYZ"
        }
      ],
      "isDisjoint": true,
      "isComplete": true
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/__tests__/test_models/transformation/test_023.json
{
  "type": "Package",
  "id": "OhzJNC6GAqAMEnf.",
  "name": "023",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "uhzJNC6GAqAMEnf_",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "BhzJNC6GAqAMEngA",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "hhzJNC6GAqAMEngB",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "RhzJNC6GAqAMEngC",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "xhzJNC6GAqAMEngD",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "xhzJNC6GAqAMEngE",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "JhzJNC6GAqAMEngF",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "phzJNC6GAqAMEngG",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "phzJNC6GAqAMEngH",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "ZhzJNC6GAqAMEngI",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "wdrJNC6GAqAMEnuJ",
      "name": "SuperClass",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["kind"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "eP7JNC6GAqAMEnuS",
      "name": "SubClass1",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["role"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "F2nJNC6GAqAMEnub",
      "name": "SubClass2",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["role"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "7bXJNC6GAqAMEnuk",
      "name": "AssociatedClass",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["relator"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["relator"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Generalization",
      "id": "gm_JNC6GAqAMEnvN",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "wdrJNC6GAqAMEnuJ"
      },
      "specific": {
        "type": "Class",
        "id": "eP7JNC6GAqAMEnuS"
      }
    },
    {
      "type": "Generalization",
      "id": "m3_JNC6GAqAMEnvR",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "wdrJNC6GAqAMEnuJ"
      },
      "specific": {
        "type": "Class",
        "id": "F2nJNC6GAqAMEnub"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "mKwpNC6GAqAMEnvY",
      "name": "SuperClassType",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "gm_JNC6GAqAMEnvN"
        },
        {
          "type": "Generalization",
          "id": "m3_JNC6GAqAMEnvR"
        }
      ],
      "isDisjoint": true,
      "isComplete": false
    },
    {
      "type": "Relation",
      "id": "IPopNC6GAqAMEnvr",
      "name": null,
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "IPopNC6GAqAMEnvs",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "F2nJNC6GAqAMEnub"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        },
        {
          "type": "Property",
          "id": "IPopNC6GAqAMEnvu",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "7bXJNC6GAqAMEnuk"
          },
          "cardinality": "1..*",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/__tests__/libs/ontouml2db/test_models/test_003_flatting_gs.json
{
  "type": "Package",
  "id": "nqMoNC6GAqAMEgu7",
  "name": "003",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "nqMoNC6GAqAMEgu8",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "PqMoNC6GAqAMEgu9",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "vqMoNC6GAqAMEgu.",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "vqMoNC6GAqAMEgu_",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "fqMoNC6GAqAMEgvA",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "_qMoNC6GAqAMEgvB",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "AaMoNC6GAqAMEgvC",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "AaMoNC6GAqAMEgvD",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "gaMoNC6GAqAMEgvE",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "QaMoNC6GAqAMEgvF",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "vqSoNC6GAqAMEg9H",
      "name": "NamedEntity",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "15doNC6GAqAMEg.A",
          "name": "name",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "QaMoNC6GAqAMEgvF"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["category"],
      "isAbstract": true,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "CIKoNC6GAqAMEg9Q",
      "name": "Person",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "CXnoNC6GAqAMEg_F",
          "name": "birth_date",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "N0voNC6GAqAMEg_S"
          },
          "cardinality": "0..1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["kind"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "E4qoNC6GAqAMEg9Z",
      "name": "Organization",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "xFoYNC6GAqAMEg_r",
          "name": "address",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "QaMoNC6GAqAMEgvF"
          },
          "cardinality": "0..1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["kind"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "N0voNC6GAqAMEg_S",
      "name": "Date",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false,
      "allowed": null,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Generalization",
      "id": "_9aoNC6GAqAMEg9e",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "vqSoNC6GAqAMEg9H"
      },
      "specific": {
        "type": "Class",
        "id": "CIKoNC6GAqAMEg9Q"
      }
    },
    {
      "type": "Generalization",
      "id": "yC6oNC6GAqAMEg9i",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "vqSoNC6GAqAMEg9H"
      },
      "specific": {
        "type": "Class",
        "id": "E4qoNC6GAqAMEg9Z"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "K_loNC6GAqAMEg9s",
      "name": "NamedEntityType",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "yC6oNC6GAqAMEg9i"
        },
        {
          "type": "Generalization",
          "id": "_9aoNC6GAqAMEg9e"
        }
      ],
      "isDisjoint": true,
      "isComplete": true
    }
  ],
  "propertyAssignments": null
}
