=== OntoUML/ontouml-js/resources/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ontouml.org/ontouml-schema/2021-02-26/Package",
  "description": "An object representing a package element. Mandatory fields: constant \"type\": \"Package\", \"id\", \"name\", \"elements\", \"propertyAssignments\". Additional fields NOT allowed.",
  "type": "object",
  "properties": {
    "type": {
      "const": "Package"
    },
    "id": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#id"
    },
    "name": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "description": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "propertyAssignments": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#propertyAssignments"
    },
    "contents": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "oneOf": [
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Package"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Class"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Relation"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/GeneralizationSet"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Generalization"
              }
            ]
          }
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": ["type", "id", "name", "description", "contents", "propertyAssignments"]
}

=== OntoUML/ontouml-js/__tests__/test_models/valids/role1.json
{
  "type": "Package",
  "id": "HK05mg6D.AAAAQbt",
  "name": "Role1",
  "description": null,
  "contents": [
    {
      "type": "Package",
      "id": "VOy5mg6D.AAAAQp1",
      "name": "Diagram1",
      "description": null,
      "propertyAssignments": null,
      "contents": [
        {
          "type": "Class",
          "id": "IsW5mg6D.AAAAQqE",
          "name": "Person",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "kind"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "ech5mg6D.AAAAQqj",
          "name": "Man",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "subkind"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "jiZ5mg6D.AAAAQrK",
          "name": "Woman",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "subkind"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "z.T5mg6D.AAAAQsY",
          "name": "Husband",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "role"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "yPX5mg6D.AAAAQtn",
          "name": "Wife",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "role"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        }
      ]
    },
    {
      "type": "Generalization",
      "id": "Tch5mg6D.AAAAQqo",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "IsW5mg6D.AAAAQqE"
      },
      "specific": {
        "type": "Class",
        "id": "ech5mg6D.AAAAQqj"
      }
    },
    {
      "type": "Generalization",
      "id": "wSZ5mg6D.AAAAQrP",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "IsW5mg6D.AAAAQqE"
      },
      "specific": {
        "type": "Class",
        "id": "jiZ5mg6D.AAAAQrK"
      }
    },
    {
      "type": "Generalization",
      "id": "EBT5mg6D.AAAAQsd",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "ech5mg6D.AAAAQqj"
      },
      "specific": {
        "type": "Class",
        "id": "z.T5mg6D.AAAAQsY"
      }
    },
    {
      "type": "Generalization",
      "id": "pPX5mg6D.AAAAQts",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "jiZ5mg6D.AAAAQrK"
      },
      "specific": {
        "type": "Class",
        "id": "yPX5mg6D.AAAAQtn"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "Br95mg6D.AAAAQsA",
      "name": "Person",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "Tch5mg6D.AAAAQqo"
        },
        {
          "type": "Generalization",
          "id": "wSZ5mg6D.AAAAQrP"
        }
      ],
      "isDisjoint": true,
      "isComplete": true
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/__tests__/test_models/transformation/test_022.json
{
  "type": "Package",
  "id": "qIwJNC6GAqAMEnPr",
  "name": "022",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "qIwJNC6GAqAMEnPs",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "GIwJNC6GAqAMEnPt",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "mIwJNC6GAqAMEnPu",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "WIwJNC6GAqAMEnPv",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "WIwJNC6GAqAMEnPw",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "2IwJNC6GAqAMEnPx",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "OIwJNC6GAqAMEnPy",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "OIwJNC6GAqAMEnPz",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "uIwJNC6GAqAMEnP0",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "eIwJNC6GAqAMEnP1",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "abstract"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "ZxCJNC6GAqAMEnd2",
      "name": "SuperClass",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "kind"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "functional-complex"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "bniJNC6GAqAMEnd_",
      "name": "SubClass1",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "role"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "functional-complex"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "6.KJNC6GAqAMEneI",
      "name": "SubClass2",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "role"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "functional-complex"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "1i6JNC6GAqAMEneR",
      "name": "AssociatedClass",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "relator"
      ],
      "isAbstract": false,
      "isDerived": false,
      "allowed": [
        "relator"
      ],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Generalization",
      "id": "ZgBJNC6GAqAMEnfA",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "ZxCJNC6GAqAMEnd2"
      },
      "specific": {
        "type": "Class",
        "id": "bniJNC6GAqAMEnd_"
      }
    },
    {
      "type": "Generalization",
      "id": "iBBJNC6GAqAMEnfE",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "ZxCJNC6GAqAMEnd2"
      },
      "specific": {
        "type": "Class",
        "id": "6.KJNC6GAqAMEneI"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "AGpJNC6GAqAMEnfN",
      "name": "SuperClassType",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "ZgBJNC6GAqAMEnfA"
        },
        {
          "type": "Generalization",
          "id": "iBBJNC6GAqAMEnfE"
        }
      ],
      "isDisjoint": true,
      "isComplete": true
    },
    {
      "type": "Relation",
      "id": "Ar5JNC6GAqAMEnfi",
      "name": null,
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "Ar5JNC6GAqAMEnfj",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "6.KJNC6GAqAMEneI"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        },
        {
          "type": "Property",
          "id": "Ar5JNC6GAqAMEnfl",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "1i6JNC6GAqAMEneR"
          },
          "cardinality": "1..*",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/__tests__/test_models/transformation/test_012.json
{
  "type": "Package",
  "id": "JBiqNC6GAqAMEjwp",
  "name": "012",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "JBiqNC6GAqAMEjwq",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "5BiqNC6GAqAMEjwr",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "5BiqNC6GAqAMEjws",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "FBiqNC6GAqAMEjwt",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "FBiqNC6GAqAMEjwu",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "lBiqNC6GAqAMEjwv",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "VBiqNC6GAqAMEjww",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "VBiqNC6GAqAMEjwx",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "1BiqNC6GAqAMEjwy",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "1BiqNC6GAqAMEjwz",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": ".qyqNC6GAqAMEj.0",
      "name": "Person",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "FGaqNC6GAqAMEj.9",
          "name": "birthDate",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "VomqNC6GAqAMEj_K"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["kind"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "VomqNC6GAqAMEj_K",
      "name": "Date",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false,
      "allowed": null,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "lc.qNC6GAqAMEj_m",
      "name": "Employee",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "1OxqNC6GAqAMEj_1",
          "name": "test",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "1BiqNC6GAqAMEjwz"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["role"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Generalization",
      "id": "qtZqNC6GAqAMEkAH",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": ".qyqNC6GAqAMEj.0"
      },
      "specific": {
        "type": "Class",
        "id": "lc.qNC6GAqAMEj_m"
      }
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/test_models/valids/role1.json
{
  "type": "Package",
  "id": "HK05mg6D.AAAAQbt",
  "name": "Role1",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "HK05mg6D.AAAAQbu",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "nK05mg6D.AAAAQbv",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "nK05mg6D.AAAAQbw",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "nK05mg6D.AAAAQbx",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "nK05mg6D.AAAAQby",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "nK05mg6D.AAAAQbz",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "nK05mg6D.AAAAQb0",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "XK05mg6D.AAAAQb1",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "XK05mg6D.AAAAQb2",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "XK05mg6D.AAAAQb3",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Package",
      "id": "VOy5mg6D.AAAAQp1",
      "name": "Diagram1",
      "description": null,
      "propertyAssignments": null,
      "contents": [
        {
          "type": "Class",
          "id": "IsW5mg6D.AAAAQqE",
          "name": "Person",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["kind"],
          "isAbstract": false,
          "isDerived": false
        },
        {
          "type": "Class",
          "id": "ech5mg6D.AAAAQqj",
          "name": "Man",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["subkind"],
          "isAbstract": false,
          "isDerived": false
        },
        {
          "type": "Class",
          "id": "jiZ5mg6D.AAAAQrK",
          "name": "Woman",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["subkind"],
          "isAbstract": false,
          "isDerived": false
        },
        {
          "type": "Class",
          "id": "z.T5mg6D.AAAAQsY",
          "name": "Husband",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["role"],
          "isAbstract": false,
          "isDerived": false
        },
        {
          "type": "Class",
          "id": "yPX5mg6D.AAAAQtn",
          "name": "Wife",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": ["role"],
          "isAbstract": false,
          "isDerived": false
        }
      ]
    },
    {
      "type": "Generalization",
      "id": "Tch5mg6D.AAAAQqo",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "IsW5mg6D.AAAAQqE"
      },
      "specific": {
        "type": "Class",
        "id": "ech5mg6D.AAAAQqj"
      }
    },
    {
      "type": "Generalization",
      "id": "wSZ5mg6D.AAAAQrP",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "IsW5mg6D.AAAAQqE"
      },
      "specific": {
        "type": "Class",
        "id": "jiZ5mg6D.AAAAQrK"
      }
    },
    {
      "type": "Generalization",
      "id": "EBT5mg6D.AAAAQsd",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "ech5mg6D.AAAAQqj"
      },
      "specific": {
        "type": "Class",
        "id": "z.T5mg6D.AAAAQsY"
      }
    },
    {
      "type": "Generalization",
      "id": "pPX5mg6D.AAAAQts",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "jiZ5mg6D.AAAAQrK"
      },
      "specific": {
        "type": "Class",
        "id": "yPX5mg6D.AAAAQtn"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "Br95mg6D.AAAAQsA",
      "name": "Person",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "Tch5mg6D.AAAAQqo"
        },
        {
          "type": "Generalization",
          "id": "wSZ5mg6D.AAAAQrP"
        }
      ],
      "isDisjoint": true,
      "isComplete": true
    }
  ],
  "propertyAssignments": null
}
