=== OntoUML/ontouml-js/resources/schemas/package.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ontouml.org/ontouml-schema/2021-02-26/Package",
  "description": "An object representing a package element. Mandatory fields: constant \"type\": \"Package\", \"id\", \"name\", \"elements\", \"propertyAssignments\". Additional fields NOT allowed.",
  "type": "object",
  "properties": {
    "type": {
      "const": "Package"
    },
    "id": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#id"
    },
    "name": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "description": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#text"
    },
    "propertyAssignments": {
      "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/definitions#propertyAssignments"
    },
    "contents": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "oneOf": [
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Package"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Class"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Relation"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/GeneralizationSet"
              },
              {
                "$ref": "https://ontouml.org/ontouml-schema/2021-02-26/Generalization"
              }
            ]
          }
        }
      ]
    }
  },
  "additionalProperties": false,
  "required": ["type", "id", "name", "description", "contents", "propertyAssignments"]
}

=== OntoUML/ontouml-js/__tests__/test_models/valids/roleMixin1.json
{
  "type": "Package",
  "id": "k_U1mg6D.AAAAQyV",
  "name": "RoleMixin1",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "U_U1mg6D.AAAAQyW",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "U_U1mg6D.AAAAQyX",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "U_U1mg6D.AAAAQyY",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0_U1mg6D.AAAAQyZ",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0_U1mg6D.AAAAQya",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0_U1mg6D.AAAAQyb",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0_U1mg6D.AAAAQyc",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0_U1mg6D.AAAAQyd",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0_U1mg6D.AAAAQye",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "M_U1mg6D.AAAAQyf",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": [
        "datatype"
      ],
      "allowed": [
        "abstract"
      ],
      "isAbstract": false,
      "isDerived": false,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Package",
      "id": "eQxLmg6D.AAAARD9",
      "name": "Diagram1",
      "description": null,
      "propertyAssignments": null,
      "contents": [
        {
          "type": "Class",
          "id": "b7Mdmg6D.AAAARAf",
          "name": "Customer",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "roleMixin"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": true,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "Sgvzmg6D.AAAARA.",
          "name": "Private Customer",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "role"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "I3gLmg6D.AAAARBf",
          "name": "Corporate Customer",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "role"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "mKoLmg6D.AAAARB5",
          "name": "Organization",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "kind"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        },
        {
          "type": "Class",
          "id": "RYMLmg6D.AAAARCr",
          "name": "Person",
          "description": null,
          "properties": null,
          "literals": null,
          "propertyAssignments": null,
          "stereotypes": [
            "kind"
          ],
          "allowed": [
            "functional-complex"
          ],
          "isAbstract": false,
          "isDerived": false,
          "isExtensional": null,
          "isPowertype": null,
          "order": null
        }
      ]
    },
    {
      "type": "Generalization",
      "id": "xgvzmg6D.AAAARBD",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "b7Mdmg6D.AAAARAf"
      },
      "specific": {
        "type": "Class",
        "id": "Sgvzmg6D.AAAARA."
      }
    },
    {
      "type": "Generalization",
      "id": "63gLmg6D.AAAARBk",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "b7Mdmg6D.AAAARAf"
      },
      "specific": {
        "type": "Class",
        "id": "I3gLmg6D.AAAARBf"
      }
    },
    {
      "type": "Generalization",
      "id": "eMULmg6D.AAAARCR",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "mKoLmg6D.AAAARB5"
      },
      "specific": {
        "type": "Class",
        "id": "I3gLmg6D.AAAARBf"
      }
    },
    {
      "type": "Generalization",
      "id": ".8CLmg6D.AAAARDJ",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "RYMLmg6D.AAAARCr"
      },
      "specific": {
        "type": "Class",
        "id": "Sgvzmg6D.AAAARA."
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "cFaLmg6D.AAAARDp",
      "name": "Customer",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "63gLmg6D.AAAARBk"
        },
        {
          "type": "Generalization",
          "id": "xgvzmg6D.AAAARBD"
        }
      ],
      "isDisjoint": true,
      "isComplete": true
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/__tests__/libs/ontouml2db/test_resources/test_025_lifting_gs_overlapping_incomplete.json
{
  "type": "Package",
  "id": "9wKZNC6GAqAMEodz",
  "name": "025",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "9wKZNC6GAqAMEod0",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "zwKZNC6GAqAMEod1",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "zwKZNC6GAqAMEod2",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "LwKZNC6GAqAMEod3",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "rwKZNC6GAqAMEod4",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "rwKZNC6GAqAMEod5",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "bwKZNC6GAqAMEod6",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "bwKZNC6GAqAMEod7",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "7wKZNC6GAqAMEod8",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "7wKZNC6GAqAMEod9",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "k2aZNC6GAqAMEor_",
      "name": "SuperClass",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["kind"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "0X6ZNC6GAqAMEosI",
      "name": "SubClass1",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["role"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "4ymZNC6GAqAMEosR",
      "name": "SubClass2",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["role"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "rPWZNC6GAqAMEosa",
      "name": "AssociatedClass",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["relator"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["relator"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Generalization",
      "id": "8POZNC6GAqAMEosf",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "k2aZNC6GAqAMEor_"
      },
      "specific": {
        "type": "Class",
        "id": "0X6ZNC6GAqAMEosI"
      }
    },
    {
      "type": "Generalization",
      "id": "UVuZNC6GAqAMEosj",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "k2aZNC6GAqAMEor_"
      },
      "specific": {
        "type": "Class",
        "id": "4ymZNC6GAqAMEosR"
      }
    },
    {
      "type": "GeneralizationSet",
      "id": "1yFZNC6GAqAMEotl",
      "name": "SuperClassType",
      "description": null,
      "propertyAssignments": null,
      "categorizer": null,
      "generalizations": [
        {
          "type": "Generalization",
          "id": "8POZNC6GAqAMEosf"
        },
        {
          "type": "Generalization",
          "id": "UVuZNC6GAqAMEosj"
        }
      ],
      "isDisjoint": false,
      "isComplete": false
    },
    {
      "type": "Relation",
      "id": "w2eZNC6GAqAMEosn",
      "name": null,
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "w2eZNC6GAqAMEoso",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "4ymZNC6GAqAMEosR"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        },
        {
          "type": "Property",
          "id": "w2eZNC6GAqAMEosq",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "rPWZNC6GAqAMEosa"
          },
          "cardinality": "1..*",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false
    }
  ],
  "propertyAssignments": null
}

=== OntoUML/ontouml-js/__tests__/libs/ontouml2db/test_models/test_016_lifting_cascade_generalization_association.json
{
  "type": "Package",
  "id": "3TWGNC6GAqAMEkzc",
  "name": "016",
  "description": null,
  "contents": [
    {
      "type": "Class",
      "id": "PTWGNC6GAqAMEkzd",
      "name": "boolean",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "AzWGNC6GAqAMEkze",
      "name": "byte",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "AzWGNC6GAqAMEkzf",
      "name": "char",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "gzWGNC6GAqAMEkzg",
      "name": "double",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "gzWGNC6GAqAMEkzh",
      "name": "float",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "QzWGNC6GAqAMEkzi",
      "name": "int",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "QzWGNC6GAqAMEkzj",
      "name": "long",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "wzWGNC6GAqAMEkzk",
      "name": "short",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "wzWGNC6GAqAMEkzl",
      "name": "void",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "IzWGNC6GAqAMEkzm",
      "name": "string",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["abstract"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "R5BGNC6GAqAMElBn",
      "name": "Person",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "aENGNC6GAqAMElC5",
          "name": "birthDate",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "E4RGNC6GAqAMElBw"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["kind"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "E4RGNC6GAqAMElBw",
      "name": "Date",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false,
      "allowed": null,
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "XBxGNC6GAqAMElB5",
      "name": "Adult",
      "description": null,
      "properties": null,
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["phase"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "kRJGNC6GAqAMElCC",
      "name": "Employee",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "FHTGNC6GAqAMElDM",
          "name": "test",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "QzWGNC6GAqAMEkzi"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["role"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["functional-complex"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Class",
      "id": "9IZGNC6GAqAMElCL",
      "name": "Employment",
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "WXbGNC6GAqAMElDd",
          "name": "salary",
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "gzWGNC6GAqAMEkzg"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "literals": null,
      "propertyAssignments": null,
      "stereotypes": ["relator"],
      "isAbstract": false,
      "isDerived": false,
      "allowed": ["relator"],
      "isExtensional": null,
      "isPowertype": null,
      "order": null
    },
    {
      "type": "Generalization",
      "id": "fGXGNC6GAqAMElDv",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "R5BGNC6GAqAMElBn"
      },
      "specific": {
        "type": "Class",
        "id": "XBxGNC6GAqAMElB5"
      }
    },
    {
      "type": "Generalization",
      "id": "kvXGNC6GAqAMElDz",
      "name": null,
      "description": null,
      "propertyAssignments": null,
      "general": {
        "type": "Class",
        "id": "XBxGNC6GAqAMElB5"
      },
      "specific": {
        "type": "Class",
        "id": "kRJGNC6GAqAMElCC"
      }
    },
    {
      "type": "Relation",
      "id": "Zx3GNC6GAqAMElD3",
      "name": null,
      "description": null,
      "properties": [
        {
          "type": "Property",
          "id": "Zx3GNC6GAqAMElD4",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "9IZGNC6GAqAMElCL"
          },
          "cardinality": "1..*",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        },
        {
          "type": "Property",
          "id": "Zx3GNC6GAqAMElD6",
          "name": null,
          "description": null,
          "propertyType": {
            "type": "Class",
            "id": "kRJGNC6GAqAMElCC"
          },
          "cardinality": "1",
          "isDerived": false,
          "isOrdered": false,
          "isReadOnly": false,
          "stereotypes": null,
          "propertyAssignments": null,
          "subsettedProperties": null,
          "redefinedProperties": null,
          "aggregationKind": "NONE"
        }
      ],
      "propertyAssignments": null,
      "stereotypes": null,
      "isAbstract": false,
      "isDerived": false
    }
  ],
  "propertyAssignments": null
}
