=== OntoUML/ontouml-js/src/schemas/ontouml.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://ontouml.org/ontouml-schema/2.0/0.1.202001091222",
  "title": "Model",
  "description": "An object that represents an OntoUML 2 ontology. Mandatory fields: constant \"type\": \"Model\", \"id\", \"name\", \"authors\", \"elements\". Additional fields allowed.",
  "type": "object",
  "properties": {
    "type": {
      "const": "Model"
    },
    "id": {
      "$ref": "#/definitions/id"
    },
    "name": {
      "$ref": "#/definitions/name"
    },
    "authors": {
      "$ref": "#/definitions/authors"
    },
    "elements": {
      "$ref": "#/definitions/elements"
    }
  },
  "required": ["type", "id", "name", "authors", "elements"],
  "definitions": {
    "Package": {
      "description": "An object representing a packge element. Mandatory fields: constant \"type\": \"Package\", \"id\", \"name\", \"elements\", \"propertyAssignments\". Additional fields allowed.",
      "type": "object",
      "properties": {
        "type": {
          "const": "Package"
        },
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "$ref": "#/definitions/name"
        },
        "elements": {
          "$ref": "#/definitions/elements"
        },
        "propertyAssignments": {
          "$ref": "#/definitions/propertyAssignments"
        }
      },
      "required": ["type", "id", "name", "elements", "propertyAssignments"]
    },
    "Class": {
      "description": "An object representing a class element. Mandatory fields: constant \"type\": \"Class\", \"id\", \"name\", \"stereotypes\", \"properties\", \"propertyAssignments\", \"isAbstract\", \"isDerived\". Additional fields allowed.",
      "type": "object",
      "properties": {
        "type": {
          "const": "Class"
        },
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "$ref": "#/definitions/name"
        },
        "stereotypes": {
          "$ref": "#/definitions/stereotypes"
        },
        "properties": {
          "$ref": "#/definitions/properties"
        },
        "propertyAssignments": {
          "$ref": "#/definitions/propertyAssignments"
        },
        "isAbstract": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isDerived": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "type",
        "id",
        "name",
        "stereotypes",
        "properties",
        "propertyAssignments",
        "isAbstract",
        "isDerived"
      ]
    },
    "Relation": {
      "description": "An object representing an relation element. Mandatory fields: constant \"type\": \"Class\", \"id\", \"name\", \"stereotypes\", \"properties\", \"propertyAssignments\". The \"properties\" array must have at least two items and is not nullable. The order of these items represents their position on a equivalent predicate, e.g., in the ternary relation \"buys-product-from(buyer,product,seller)\", the order of items representing these entities must follow the order \"buyer\" (in properties[0]), \"product\" (in properties[1]), and \"seller\" (in properties[2]). Relation elements are also used to represent derivation relations, in which case they must contain the stereotype \"ontouml/derivation\" and have only 2 properties, the first being a Relation element and the second a Class element. Additional fields allowed. Ordered properties.",
      "type": "object",
      "properties": {
        "type": {
          "const": "Relation"
        },
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "$ref": "#/definitions/name"
        },
        "stereotypes": {
          "$ref": "#/definitions/stereotypes"
        },
        "properties": {
          "allOf": [
            {
              "$ref": "#/definitions/properties"
            }
          ],
          "minItems": 2
        },
        "propertyAssignments": {
          "$ref": "#/definitions/propertyAssignments"
        },
        "isAbstract": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isDerived": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "type",
        "id",
        "name",
        "stereotypes",
        "properties",
        "propertyAssignments",
        "isAbstract",
        "isDerived"
      ],
      "not": {
        "properties": {
          "properties": {
            "type": "null"
          }
        }
      }
    },
    "Generalization": {
      "description": "An object representing a generalization element. Mandatory fields: constant \"type\": \"Generalization\", \"id\", \"name\", \"general\", \"specific\", \"propertyAssignments\". Additional fields allowed.",
      "type": "object",
      "properties": {
        "type": {
          "const": "Generalization"
        },
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "$ref": "#/definitions/name"
        },
        "general": {
          "$ref": "#/definitions/reference"
        },
        "specific": {
          "$ref": "#/definitions/reference"
        },
        "propertyAssignments": {
          "$ref": "#/definitions/propertyAssignments"
        }
      },
      "required": [
        "type",
        "id",
        "name",
        "general",
        "specific",
        "propertyAssignments"
      ]
    },
    "GeneralizationSet": {
      "description": "An object representing a generalization set element. Mandatory fields: constant \"type\": \"GeneralizationSet\", \"id\", \"name\", \"isDisjoint\", \"isComplete\", \"categorizer\", \"generalizations\", \"propertyAssignments\". Additional fields allowed.",
      "type": "object",
      "properties": {
        "type": {
          "const": "GeneralizationSet"
        },
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "$ref": "#/definitions/name"
        },
        "isDisjoint": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isComplete": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "categorizer": {
          "oneOf": [
            {
              "$ref": "#/definitions/reference"
            },
            {
              "type": "null"
            }
          ]
        },
        "generalizations": {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/reference"
          }
        },
        "propertyAssignments": {
          "$ref": "#/definitions/propertyAssignments"
        }
      },
      "required": [
        "type",
        "id",
        "name",
        "isDisjoint",
        "isComplete",
        "categorizer",
        "generalizations",
        "propertyAssignments"
      ]
    },
    "Property": {
      "description": "An object representing a property element. This represents properties exhibited by instances of classes, relations and derivation relations, where in the first case properties are analougous to attrbutes while in the second and third cases properties are analogous to association ends. Mandatory fields: constant \"type\": \"Property\", \"id\", \"name\" \"cardinality\", \"stereotypes\", \"propertyAssignments\", \"subsettedProperties\", \"redefinedProperties\", \"aggregationKind\", \"isDerived\", \"isOrdered\", \"isReadOnly\". Additional fields allowed.",
      "type": "object",
      "properties": {
        "type": {
          "const": "Property"
        },
        "id": {
          "$ref": "#/definitions/id"
        },
        "name": {
          "$ref": "#/definitions/name"
        },
        "cardinality": {
          "oneOf": [
            {
              "type": "string",
              "minLength": 1
            },
            {
              "type": "null"
            }
          ]
        },
        "stereotypes": {
          "$ref": "#/definitions/stereotypes"
        },
        "propertyAssignments": {
          "$ref": "#/definitions/propertyAssignments"
        },
        "subsettedProperties": {
          "oneOf": [
            {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "#/definitions/reference"
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "redefinedProperties": {
          "oneOf": [
            {
              "type": "array",
              "minItems": 1,
              "uniqueItems": true,
              "items": {
                "$ref": "#/definitions/reference"
              }
            },
            {
              "type": "null"
            }
          ]
        },
        "aggregationKind": {
          "oneOf": [
            {
              "type": "string",
              "enum": ["NONE", "SHARED", "COMPOSITE"]
            },
            {
              "type": "null"
            }
          ]
        },
        "isDerived": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isOrdered": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        },
        "isReadOnly": {
          "oneOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ]
        }
      },
      "required": [
        "type",
        "id",
        "name",
        "cardinality",
        "stereotypes",
        "propertyAssignments",
        "subsettedProperties",
        "redefinedProperties",
        "aggregationKind",
        "isDerived",
        "isOrdered",
        "isReadOnly"
      ]
    },
    "authors": {
      "description": "A non-empty array of strings representing names of an object's authors. Nullable.",
      "oneOf": [
        {
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "elements": {
      "description": "A non-empty array of objects representing model elements. May contain objects representing one of the following types of model elements: \"Package\", \"Class\", \"Relation\", \"Generalization\", \"GeneralizationSet\". Nullable.",
      "oneOf": [
        {
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "oneOf": [
              {
                "$ref": "#/definitions/Package"
              },
              {
                "$ref": "#/definitions/Class"
              },
              {
                "$ref": "#/definitions/Relation"
              },
              {
                "$ref": "#/definitions/Generalization"
              },
              {
                "$ref": "#/definitions/GeneralizationSet"
              }
            ]
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "id": {
      "description": "A non-empty string representing an object's unique identifier.",
      "type": "string",
      "minLength": 1
    },
    "name": {
      "description": "A non-empty string representing an object's name. Nullable.",
      "oneOf": [
        {
          "type": "string",
          "minLength": 1
        },
        {
          "type": "null"
        }
      ]
    },
    "properties": {
      "description": "A non-empty array of Property elements representing properties exhibited by instances of the container model element. Nullable.",
      "oneOf": [
        {
          "type": "array",
          "minItems": 1,
          "items": {
            "$ref": "#/definitions/Property"
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "propertyAssignments": {
      "description": "A non-empty array of key-value pairs representing assignments to instantiated properties instantiated by the container object. Assignments may have any key name, but its values are restricted to null, booleans, numbers, strings, references or arrays of these. Assignments are analogous to UML's notion of tagged values. Nullable.",
      "oneOf": [
        {
          "type": "object",
          "minProperties": 1
        },
        {
          "type": "null"
        }
      ],
      "additionalProperties": {
        "oneOf": [
          {
            "type": "null"
          },
          {
            "type": "boolean"
          },
          {
            "type": "number"
          },
          {
            "type": "string"
          },
          {
            "$ref": "#/definitions/reference"
          },
          {
            "type": "array",
            "uniqueItems": true,
            "minItems": 1,
            "items": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "number"
                },
                {
                  "type": "string"
                },
                {
                  "$ref": "#/definitions/reference"
                }
              ]
            }
          }
        ]
      }
    },
    "reference": {
      "description": "An object representing a singular reference to a model element. Mandatory fields: \"type\", \"id\".",
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "Package",
            "Class",
            "Relation",
            "Generalization",
            "GeneralizationSet",
            "Property"
          ]
        },
        "id": {
          "$ref": "#/definitions/id"
        }
      },
      "required": ["type", "id"],
      "additionalProperties": false
    },
    "stereotypes": {
      "description": "A non-empty array of non-empty strings representing stereotypes of its container object. Nullable.",
      "oneOf": [
        {
          "type": "array",
          "uniqueItems": true,
          "minItems": 1,
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        {
          "type": "null"
        }
      ]
    }
  }
}

=== OntoUML/ontouml-js/test_models/others/packages.json
{
  "type": "Model",
  "id": "qJdeWA6AUB0UtAWl",
  "name": "untitled",
  "authors": ["claudenirmf"],
  "elements": [
    {
      "type": "Class",
      "id": "qJdeWA6AUB0UtAWm",
      "name": "boolean",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "Q5deWA6AUB0UtAWn",
      "name": "byte",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "Q5deWA6AUB0UtAWo",
      "name": "char",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "w5deWA6AUB0UtAWp",
      "name": "double",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "w5deWA6AUB0UtAWq",
      "name": "float",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "I5deWA6AUB0UtAWr",
      "name": "int",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "I5deWA6AUB0UtAWs",
      "name": "long",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "o5deWA6AUB0UtAWt",
      "name": "short",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "o5deWA6AUB0UtAWu",
      "name": "void",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Class",
      "id": "Y5deWA6AUB0UtAWv",
      "name": "string",
      "description": null,
      "properties": null,
      "propertyAssignments": null,
      "stereotypes": ["datatype"],
      "isAbstract": false,
      "isDerived": false
    },
    {
      "type": "Package",
      "id": "Yx3eWA6AUB0UtAk5",
      "name": "1.",
      "description": null,
      "propertyAssignments": null,
      "elements": [
        {
          "type": "Package",
          "id": "Wkc.WA6AUB0UtAlq",
          "name": "1.1",
          "description": null,
          "propertyAssignments": null,
          "elements": [
            {
              "type": "Package",
              "id": "uYi.WA6AUB0UtAl8",
              "name": "1.1.1",
              "description": null,
              "propertyAssignments": null,
              "elements": null
            }
          ]
        },
        {
          "type": "Package",
          "id": "iz8.WA6AUB0UtAlz",
          "name": "1.2",
          "description": null,
          "propertyAssignments": null,
          "elements": null
        }
      ]
    },
    {
      "type": "Package",
      "id": "5Og.WA6AUB0UtAlC",
      "name": "2.",
      "description": null,
      "propertyAssignments": null,
      "elements": null
    },
    {
      "type": "Package",
      "id": "7Fw.WA6AUB0UtAlL",
      "name": "3.",
      "description": null,
      "propertyAssignments": null,
      "elements": [
        {
          "type": "Package",
          "id": "gNW.WA6AUB0UtAmV",
          "name": "3.1",
          "description": null,
          "propertyAssignments": null,
          "elements": null
        },
        {
          "type": "Package",
          "id": "xC..WA6AUB0UtAmn",
          "name": "3.3",
          "description": null,
          "propertyAssignments": null,
          "elements": null
        },
        {
          "type": "Package",
          "id": "cDO.WA6AUB0UtAme",
          "name": "3.2",
          "description": null,
          "propertyAssignments": null,
          "elements": [
            {
              "type": "Package",
              "id": "2sT.WA6AUB0UtAnV",
              "name": "3.2.1",
              "description": null,
              "propertyAssignments": null,
              "elements": [
                {
                  "type": "Package",
                  "id": "7kH.WA6AUB0UtAne",
                  "name": "3.2.1.1",
                  "description": null,
                  "propertyAssignments": null,
                  "elements": null
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
